export const ActionTypes = {
  SET_PLAYERS: "SET_PLAYERS",
  ADD_PLAYER: "ADD_PLAYER",
  UPDATE_PLAYER: "UPDATE_PLAYER",
  REMOVE_SELECTED_PLAYER: "REMOVE_SELECTED_PLAYER",
}

export const TypesMembers = {
  SET_MEMBERS: "SET_MEMBERS",
  SET_MEMBERS_FILTER: "SET_MEMBERS_FILTER",
  ADD_MEMBERS: "ADD_MEMBERS",
  UPDATE_MEMBERS: "UPDATE_MEMBERS",
  UPDATE_MEMBERS_PAYMENT: "UPDATE_MEMBERS_PAYMENT",
  REMOVE_SELECTED_MEMBERS: "REMOVE_SELECTED_MEMBERS",
}

export const TypesMovimientos = {
  SET_MOVIMIENTOS_EGRESOS: "SET_MOVIMIENTOS_EGRESOS",
  SET_MOVIMIENTOS_INGRESOS: "SET_MOVIMIENTOS_INGRESOS",
  SET_MOVIMIENTO_FILTER: "SET_MOVIMIENTO_FILTER",
  ADD_MOVIMIENTO: "ADD_MOVIMIENTO",
  UPDATE_MOVIMIENTO: "UPDATE_MOVIMIENTO",
  ADD_SALDO_INGRESOS: "ADD_SALDO_INGRESOS",
  ADD_SALDO_EGRESOS: "ADD_SALDO_EGRESOS",
  ADD_SALDO_DIFERENCIA: "ADD_SALDO_DIFERENCIA",
  REMOVE_SELECTED_MOVIMIENTO: "REMOVE_SELECTED_MOVIMIENTO",
}
